Repository ArtTalkTalk/ArtTalkTalk_frontend, pull requests merged in 2024-02, with the labels that each got.

#36 [김윤후] 구글 소셜 로그인 기능 구현
  package-lock.json
  package.json
  src/app/(unauth)/_components/GoogleLoginButton.tsx
  src/app/(unauth)/_components/LoginPage.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/contexts/AuthContext.tsx
Labels: ✨ feat, 🎨 style

#41 [김윤후] 카드 컴포넌트 추가 구현
  public/assets/icons/KebabDropDown.svg
  public/assets/images/FreeImage.png
  public/assets/images/KebabImage.png
  src/app/(auth)/_component/MyPage.tsx
  src/components/Button/KebabButton.tsx
  src/components/Card/Card.tsx
Labels: ✨ feat, 🎨 style

#42 [김윤후] 상단 네비게이션 바 검색 기능 추가 구현
  public/assets/icons/CancelIcon.svg
  src/components/NavBar/SearchBar.tsx
Labels: ✨ feat, 🎨 style

#44 [송규경] 카카오 및 네이버 SNS 로그인 구현 (구글 로그인 삭제)
  next.config.mjs
  package-lock.json
  package.json
  public/assets/icons/youthLogo.svg
  public/assets/images/kakaoLogo.png
  public/assets/images/loginBg.png
  public/assets/images/naverLogo.png
  public/assets/images/youthLogo.png
  src/api/auth/postUserId.ts
  src/api/cards/.gitkeep
  src/api/users/.gitkeep
  src/app/(auth)/_component/MyPage.tsx
  src/app/(unauth)/_components/GoogleLoginButton.tsx
  src/app/(unauth)/_components/LoginPage.tsx
  src/app/(unauth)/login/_components/KakaoLoginButton.tsx
  src/app/(unauth)/login/_components/NaverLoginButton.tsx
  src/app/(unauth)/login/_components/RedirectToHome.tsx
  src/app/(unauth)/login/postFlow/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavigatorBox.tsx
  src/components/NavBar/ProfileImgDropDown.tsx
  src/components/NavBar/SearchBar.tsx
  src/components/SideBar/ProfileIcon.tsx
  src/components/SideBar/SideBar.tsx
  src/contexts/AuthContext.tsx
  src/contexts/AuthSessionProvider.tsx
  src/lib/axios.ts
  src/store/authSlice.ts
  src/store/index.ts
  src/store/zustand.types.ts
  src/styles/tailwind.css
  src/types/cards.ts
  src/types/users.ts
  src/utils/ReactQueryProvider.tsx
  tailwind.config.ts
Labels: ✨ feat, 🎨 style

#47 [김윤후] 사이드 네비게이션 바 추가 구현
  public/assets/icons/LinkIcon.svg
  src/app/(auth)/_component/MyPage.tsx
  src/components/SideBar/AddLinkIcon.tsx
  src/components/SideBar/LinkIcon.tsx
  src/components/SideBar/SideBar.tsx
  src/styles/tailwind.css
Labels: ✨ feat, 🎨 style

#51 [송규경] 카드 컴포넌트 hover 시 이미지 확대 구현
  public/assets/images/FreeImage.png
  public/assets/images/freeFlag.png
  src/api/auth/postUserId.ts
  src/app/(auth)/layout.tsx
  src/app/(unauth)/login/_components/NaverLoginButton.tsx
  src/app/(unauth)/login/_components/RedirectToHome.tsx
  src/components/Button/KebabButton.tsx
  src/components/Card/Card.tsx
  src/components/NavBar/NavigatorBox.tsx
  src/components/NavBar/ProfileImgDropDown.tsx
  src/lib/axios.ts
  src/types/users.ts
Labels: ✨ feat, 🎨 style

#57 [김윤후] fetch 공용 함수 구현
  src/api/fetchRequestHandler.ts
Labels: ✨ feat

#53 [김윤후] 마이페이지 데이터 연동
  src/api/users/.gitkeep
  src/api/users/getUser.ts
  src/app/(auth)/_component/MyPage.tsx
  src/components/Card/CardContainer.tsx
  src/components/Card/NoContent.tsx
  src/components/NavBar/MessageIcon.tsx
  src/components/NavBar/NavigatorBox.tsx
  src/components/NavBar/ProfileImgDropDown.tsx
  src/components/SideBar/SideBar.tsx
  src/styles/tailwind.css
Labels: ✨ feat, 🎨 style

#60 [송규경] 회원가입 페이지 프레임 구현 및 타입 추가 정의
  src/api/auth/postUserId.ts
  src/app/(unauth)/_components/SignupPage.tsx
  src/app/(unauth)/login/_components/RedirectToHome.tsx
  src/app/(unauth)/signup/page.tsx
  src/lib/axios.ts
  src/types/auth.ts
  src/types/cards.ts
  src/types/users.ts
Labels: ⚙ chore, 🎨 style

#61 [송규경] not-found 페이지 구현 및 infinite flow text 컴포넌트 구현
  public/assets/images/logo.png
  public/assets/images/youthLogo.png
  src/app/(unauth)/artist/[id]/page.tsx
  src/app/not-found.tsx
  src/components/InfiniteText.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/ProfileImgDropDown.tsx
  src/components/SideBar/SideBar.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ feat, 🎨 style

#55 [송민혁] 게시물 업로드 페이지 초안
  package-lock.json
  package.json
  public/assets/icons/cloud_upload.svg
  public/assets/icons/saleFlag.svg
  public/assets/icons/shareFlag.svg
  public/assets/images/OnSaleImage.png
  src/app/(auth)/flow/upload/page.tsx
  src/app/(root-modal)/LoginModal/LoginModal.tsx
  src/app/(root-modal)/UploadModal/UploadModal.tsx
  src/app/(root-modal)/UploadModal/_components/BeforeUploadImage.tsx
  src/app/(root-modal)/UploadModal/_components/StatusLabelsGroup.tsx
  src/app/(root-modal)/UploadModal/_components/TextEditor.css
  src/app/(root-modal)/UploadModal/_components/TextEditor.tsx
  src/app/(root-modal)/_components/ModalHeader/ModalHeader.tsx
  src/components/Button/Category/CategoryButton.tsx
  src/components/Button/Category/CategoryButtonGroup.tsx
  src/components/Button/Modal/ModalActionButton.tsx
  src/components/Button/Modal/ModalCloseButton.tsx
  src/components/Button/PrimaryButton.tsx
  src/styles/tailwind.css
  src/utils/date.ts
Labels: ✨ feat

#66 [김윤후] 댓글 컴포넌트 구현
  public/assets/icons/BlackComment.svg
  public/assets/icons/CommentSend.svg
  public/assets/icons/Free.svg
  public/assets/icons/RedLike.svg
  public/assets/icons/Selling.svg
  public/assets/icons/WhiteComment.svg
  public/assets/icons/WhiteLike.svg
  src/components/Comment/BlackComment.tsx
  src/components/Comment/Comment.tsx
  src/components/Comment/CommentContainer.tsx
  src/components/Comment/CommentSend.tsx
  src/components/Comment/Free.tsx
  src/components/Comment/RedLike.tsx
  src/components/Comment/Selling.tsx
  src/components/Comment/WhiteComment.tsx
  src/components/Comment/WhiteLike.tsx
  tailwind.config.ts
Labels: ✨ feat, 🎨 style

#67 [송규경] 메인페이지 구현 및 CardContainer Grid 구현
  public/assets/images/loginBg.png
  src/api/axios.ts
  src/app/(auth)/_component/MyPage.tsx
  src/app/(root-modal)/UploadModal/UploadModal.tsx
  src/app/(root-modal)/UploadModal/_components/StatusLabelsGroup.tsx
  src/app/(unauth)/_components/Main.tsx
  src/app/(unauth)/_components/Main/MainCardSection.tsx
  src/app/(unauth)/_components/Main/MainLabelsGroup.tsx
  src/app/(unauth)/art/[id]/page.tsx
  src/components/Button/Category/CategoryButton.tsx
  src/components/Card/Card.tsx
  src/components/Card/CardContainer.tsx
  src/components/Card/NoContent.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavigatorBox.tsx
  src/components/NavBar/SearchBar.tsx
  src/components/SideBar/SideBar.tsx
  src/styles/tailwind.css
  tailwind.config.ts
Labels: 🔨 refactor, ✨ feat, 🎨 style, ✏ fix

#73 [송규경] 여러 필수 수정사항들 반영
  public/assets/images/CommentImage.png
  src/api/users/getUser.ts
  src/app/(auth)/_component/MyPage.tsx
  src/app/(root-modal)/UploadModal/UploadModal.tsx
  src/app/(root-modal)/_components/ModalContainer/ModalContainer.tsx
  src/app/(unauth)/_components/Main.tsx
  src/app/(unauth)/_components/Main/MainCardSection.tsx
  src/components/Card/Card.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavigatorBox.tsx
  src/components/NavBar/ProfileImgDropDown.tsx
  src/hooks/useNotScroll.ts
  src/styles/tailwind.css
  tailwind.config.ts
Labels: ⚙ chore, 🔨 refactor, ✨ feat, 🎨 style

#77 [김윤후] 작가 상세 페이지 구현
  src/app/(unauth)/_components/Artist/ArtistCardSection.tsx
  src/app/(unauth)/_components/Artist/ArtistLabelsGroup.tsx
  src/app/(unauth)/artist/[id]/page.tsx
  src/components/Button/Category/CategoryButton.tsx
  src/components/SideBar/SideBar.tsx
  src/styles/tailwind.css
Labels: ✨ feat, 🎨 style

#78 [이규호] 프로필 수정 페이지 구현
  package-lock.json
  package.json
  src/api/image/deleteImageFile.ts
  src/api/image/postImageFile.ts
  src/api/links/deleteLinks.ts
  src/api/links/postLinks.ts
  src/app/(auth)/_component/EditProfilePage.tsx
  src/app/(auth)/layout.tsx
  src/components/Button/PrimaryButton.tsx
  src/components/Input/Input.tsx
  src/components/Input/LinkInput.tsx
  src/components/ProfilePage/ProfilePage.tsx
  src/components/SvgComponents/BinIcon.tsx
  src/components/SvgComponents/EditIcon.tsx
  src/components/SvgComponents/PlusButtonIcon.tsx
  src/components/SvgComponents/SaveIcon.tsx
  src/components/SvgComponents/UpLoadIcon.tsx
  src/constants/InputErrorMsg.ts
  src/constants/InputErrorRules.ts
  src/styles/tailwind.css
  tailwind.config.ts
Labels: ⚙ chore, 🔨 refactor, ✨ feat, 🎨 style, ✏ fix

#80 [김윤후] 작품 상세 페이지 구현
  package-lock.json
  package.json
  public/assets/icons/Expand.svg
  public/assets/icons/Quit.svg
  src/app/(root-modal)/ArtModal/ArtModal.tsx
  src/app/(root-modal)/_components/ModalContainer/ModalContainer.tsx
  src/app/(root-modal)/_components/ModalHeader/ArtModalHeader.tsx
  src/app/(root-modal)/_components/index.ts
  src/components/Comment/CommentContainer.tsx
  src/components/SlideContainer/Expand.tsx
  src/components/SlideContainer/Quit.tsx
  src/components/SlideContainer/SlideContainer.tsx
  src/styles/tailwind.css
  tailwind.config.ts
Labels: ✨ feat, 🎨 style

#84 [송규경] 작품 업로드 및 작품 상세 모달의 뒷 배경(children) 조건부 렌더링
  src/app/(auth)/_component/MyPage.tsx
  src/app/(auth)/_component/MyPage/MainContainer.tsx
  src/app/(auth)/upload/_component/ParallelChildren.tsx
  src/app/(auth)/upload/page.tsx
  src/app/(root-modal)/ArtModal/ArtModal.tsx
  src/app/(unauth)/_components/Artist/ArtistCardSection.tsx
  src/app/(unauth)/_components/ArtistPage.tsx
  src/app/(unauth)/_components/Main/MainCardSection.tsx
  src/app/(unauth)/art/[id]/page.tsx
  src/app/(unauth)/art/_components/ParallelChildren.tsx
  src/app/(unauth)/artist/[id]/page.tsx
  src/components/Button/Category/CategoryButton.tsx
  src/components/Button/Category/CategoryButtonGroup.tsx
  src/components/Button/PrimaryButton.tsx
  src/components/Card/Card.tsx
  src/components/Card/CardContainer.tsx
  src/components/Comment/CommentContainer.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavigatorBox.tsx
  src/components/NavBar/NavigatorBoxButton.tsx
  src/components/SlideContainer/SlideContainer.tsx
  src/store/artworkSlice.ts
  src/store/zustand.types.ts
  src/styles/tailwind.css
  tailwind.config.ts
Labels: ✨ feat, 🎨 style, ✏ fix

#87 [이규호] 회원가입 페이지 구현
  src/api/links/postLinks.ts
  src/app/(auth)/_component/EditProfilePage.tsx
  src/app/(auth)/_component/MyPage.tsx
  src/app/(unauth)/_components/ArtistPage.tsx
  src/app/(unauth)/_components/SignupPage.tsx
  src/components/Input/Input.tsx
  src/components/Input/LinkInput.tsx
  src/components/NavBar/NavigatorBox.tsx
  src/components/ProfilePage/ProfilePage.tsx
  src/styles/tailwind.css
Labels: ✨ feat, 🎨 style, ✏ fix

#85 [송민혁] DND / API 연동 / 수정안 반영
  package-lock.json
  package.json
  public/assets/icons/AddPhoto.svg
  public/assets/icons/Close.svg
  public/assets/icons/Trashcan.svg
  public/assets/icons/WhiteAddPhoto.svg
  src/api/auth/postUserId.ts
  src/api/upload/postArtwork.ts
  src/api/upload/postUploadImageFile.ts
  src/app/(root-modal)/UploadModal/UploadModal.tsx
  src/app/(root-modal)/UploadModal/_components/AddImageButton.tsx
  src/app/(root-modal)/UploadModal/_components/DeleteAllImageButton.tsx
  src/app/(root-modal)/UploadModal/_components/PreviewImage.tsx
  src/app/(root-modal)/UploadModal/_components/StatusLabelsGroup.tsx
  src/app/(root-modal)/UploadModal/_components/TextEditor.css
  src/app/(root-modal)/_components/ModalContainer/ModalContainer.tsx
  src/app/(unauth)/login/_components/RedirectToHome.tsx
  src/styles/tailwind.css
  src/types/artworks.ts
Labels: ✨ feat, 🎨 style, ✏ fix

#93 [송규경] 로그인 구현 및 css 원상복귀, swiper 이미지 개수 조정
  package-lock.json
  package.json
  src/api/auth/getMe.ts
  src/api/auth/postSocialInfo.ts
  src/api/auth/postUserId.ts
  src/api/axios.ts
  src/api/cards/.gitkeep
  src/api/fetchRequestHandler.ts
  src/api/users/getMyPage.ts
  src/app/(root-modal)/ArtModal/ArtModal.tsx
  src/app/(unauth)/login/_components/KakaoLoginButton.tsx
  src/app/(unauth)/login/_components/NaverLoginButton.tsx
  src/app/(unauth)/login/_components/RedirectToHome.tsx
  src/components/Comment/CommentContainer.tsx
  src/components/NavBar/ProfileImgDropDown.tsx
  src/components/SlideContainer/SlideContainer.tsx
  src/hooks/useBrowserSize.ts
  src/hooks/useIfLogin.ts
  src/store/authSlice.ts
  src/store/index.ts
  src/store/zustand.types.ts
  src/styles/tailwind.css
Labels: 🔨 refactor, ✨ feat, 🎨 style, ✏ fix

#95 [김윤후] 로그인/회원가입 페이지 반응형 디자인 구현
  src/app/(unauth)/_components/LoginPage.tsx
  src/app/(unauth)/_components/SignupPage.tsx
  src/components/Input/Input.tsx
  src/components/Input/LinkInput.tsx
  src/components/ProfilePage/ProfilePage.tsx
  src/styles/tailwind.css
  tailwind.config.ts
Labels: ✨ feat, 🎨 style

#96 [송규경] 회원가입 및 회원가입 시 정보 업데이트 구현
  src/api/image/postImageFile.ts
  src/app/(unauth)/_components/SignupPage.tsx
  src/app/(unauth)/login/_components/NaverLoginButton.tsx
  src/app/(unauth)/login/_components/RedirectToHome.tsx
  src/components/Input/Input.tsx
  src/components/NavBar/ProfileImgDropDown.tsx
  src/components/ProfilePage/ProfilePage.tsx
  src/components/SideBar/SideBar.tsx
  src/hooks/useIfLogin.ts
  src/types/users.ts
  src/utils/getUserInfo.ts
Labels: ✨ feat

#99 [송규경] 🚨핫픽스: 처음 접속시 isLogin이 1초 뒤 false가 되게끔 수정
  src/components/NavBar/NavigatorBoxButton.tsx
Labels: ✨ feat

#100 [김윤후] 전체 피드 페이지 무한스크롤 구현, 무한스크롤 커스텀 훅 구현(재사용성)
  package-lock.json
  package.json
  src/api/artworks/getArtworks.ts
  src/app/layout.tsx
  src/components/Card/Card.tsx
  src/components/Card/CardContainer.tsx
  src/hooks/useObserver.ts
  src/utils/ReactQueryProvider.tsx
Labels: 🔨 refactor, ✨ feat

#106 [송규경] 회원가입 페이지 리다이렉트 구현 및 카드 이미지 hover시 스타일 픽스
  src/api/auth/getMe.ts
  src/api/axios.ts
  src/app/(unauth)/signup/layout.tsx
  src/components/Card/Card.tsx
  src/components/CheckRegular.tsx
  src/components/ProfilePage/ProfilePage.tsx
Labels: ✨ feat, 🎨 style

#107 [김윤후] CardContainer 컴포넌트 리팩토링
  src/app/(auth)/_component/MyPage/MainContainer.tsx
  src/app/(unauth)/_components/Artist/ArtistCardSection.tsx
  src/app/(unauth)/_components/Main/MainCardSection.tsx
  src/components/Card/CardContainer.tsx
Labels: 🔨 refactor, ✨ feat

#105 [송민혁] dnd 기능 및 미리보기 순서보장
  public/assets/icons/Trashcan.svg
  public/assets/icons/cloud_upload.svg
  src/api/upload/postArtwork.ts
  src/app/(root-modal)/UploadModal/UploadModal.tsx
  src/app/(root-modal)/UploadModal/_components/AddImageButton.tsx
  src/app/(root-modal)/UploadModal/_components/BeforeUploadImage.tsx
  src/app/(root-modal)/UploadModal/_components/DeleteAllImageButton.tsx
  src/app/(root-modal)/UploadModal/_components/PreviewImage.tsx
  src/app/(root-modal)/UploadModal/_components/StatusLabelsGroup.tsx
  src/app/(root-modal)/UploadModal/_components/TextEditor.css
  src/app/(root-modal)/UploadModal/_components/TextEditor.tsx
  src/components/ProfilePage/ProfilePage.tsx
  src/styles/tailwind.css
  tailwind.config.ts
Labels: ✨ feat, ✏ fix

#120 [송규경] 준회원일 경우, 마이페이지 및 작품 올리기 대응 및 작품 업로드/작품상세 페이지 리팩토링
  public/assets/icons/BlackLike.svg
  public/assets/icons/UpArraw.svg
  public/assets/icons/WhiteLike.svg
  public/assets/icons/comment.svg
  src/api/axios.ts
  src/api/fetchRequestHandler.ts
  src/app/(auth)/_component/MyPage.tsx
  src/app/(auth)/mypage/layout.tsx
  src/app/(root-modal)/ArtModal/ArtModal.tsx
  src/app/(root-modal)/AskForSignupModal/AskForSignupModal.tsx
  src/app/(root-modal)/UploadModal/UploadModal.tsx
  src/app/(root-modal)/_components/ModalContainer/ModalContainer.tsx
  src/app/(root-modal)/_components/ModalHeader/ArtModalHeader.tsx
  src/app/(unauth)/_components/ArtistPage.tsx
  src/app/(unauth)/artist/layout.tsx
  src/components/CheckLogin.tsx
  src/components/Comment/BlackLike.tsx
  src/components/Comment/CommentContainer.tsx
  src/components/Comment/RedLike.tsx
  src/components/NavBar/NavigatorBox.tsx
  src/components/NavBar/NavigatorBoxButton.tsx
  src/components/SideBar/SideBar.tsx
  src/hooks/useInfiniteData.tsx
  src/hooks/useScrollY.ts
  src/store/zustand.types.ts
  src/styles/tailwind.css
  src/types/users.ts
  tailwind.config.ts
Labels: 🔨 refactor, ✨ feat, 🎨 style

#122 [이규호] 프로필 수정 페이지
  package-lock.json
  package.json
  src/api/links/deleteLinks.ts
  src/api/links/postLinks.ts
  src/api/links/putLinks.ts
  src/app/(auth)/_component/DeleteUserPage.tsx
  src/app/(auth)/_component/EditProfilePage.tsx
  src/app/(auth)/editProfile/page.tsx
  src/app/(auth)/myAccount/@deleteProfile/_component/DeleteBox.tsx
  src/app/(auth)/myAccount/@deleteProfile/page.tsx
  src/app/(auth)/myAccount/@editProfile/page.tsx
  src/app/(auth)/myAccount/layout.tsx
  src/app/(root-modal)/WithdrawalModal/WithdrawalModal.tsx
  src/components/Input/Input.tsx
  src/components/Input/LinkInput.tsx
  src/components/NavBar/ProfileImgDropDown.tsx
  src/components/ProfilePage/ProfilePage.tsx
  src/components/SideBar/SideBar.tsx
  src/components/Tab/Tab.tsx
  src/styles/tailwind.css
  src/types/input.ts
  src/types/users.ts
Labels: 🚨 help, ✨ feat, 🎨 style, ✏ fix

#129 [송민혁] 업로드 모달 헤더에 프로필 정보 연동
  src/api/users/getUser.ts
  src/app/(root-modal)/UploadModal/UploadModal.tsx
  src/app/(root-modal)/_components/ModalHeader/ModalHeader.tsx
Labels: ✨ feat

#134 [송규경] 핫픽스: 로그아웃 시 로컬스토리지 store key 삭제 안되는 오류 수정 및 배포 사이트 관련 핫픽스
  src/api/axios.ts
  src/components/NavBar/NavigatorBox.tsx
  src/components/NavBar/ProfileImgDropDown.tsx
  src/components/SideBar/SideBar.tsx
Labels: ✏ fix

#143 [이규호] 댓글 CRUD 구현, 댓글 무한스크롤 구현, dayjs 라이브러리 공용 함수 구현
  package-lock.json
  package.json
  src/api/comments/deleteComments.ts
  src/api/comments/getComments.ts
  src/api/comments/postComments.ts
  src/api/comments/putComments.ts
  src/app/(root-modal)/ArtModal/ArtModal.tsx
  src/components/Card/Card.tsx
  src/components/Card/CardContainer.tsx
  src/components/Comment/Comment.tsx
  src/components/Comment/CommentContainer.tsx
  src/components/FallbackUI/Card/CardImageFallbackUI.tsx
  src/components/SlideContainer/SlideContainer.tsx
  src/hooks/useInfiniteData.tsx
  src/types/comment.ts
  src/utils/dayjs.ts
  tsconfig.json
Labels: 🔨 refactor, ✨ feat, 🎨 style

#144 [송규경] 작품 상세 모달에서 작품 수정 및 삭제 구현, 용량 큰 파일의 경우 경고 모달 띄우기 등 여러가지 구현
  public/assets/icons/menu.svg
  src/api/axios.ts
  src/app/(auth)/myAccount/layout.tsx
  src/app/(no-access)/NoAccess/page.tsx
  src/app/(root-modal)/ArtModal/ArtModal.tsx
  src/app/(root-modal)/AskForDeleteModal/AskForDeleteModal.tsx
  src/app/(root-modal)/EditUploadModal/EditUploadModal.tsx
  src/app/(root-modal)/UploadModal/UploadModal.tsx
  src/app/(root-modal)/UploadModal/_components/StatusLabelsGroup.tsx
  src/app/(root-modal)/UploadModal/_components/TextEditor.css
  src/app/(root-modal)/UploadModal/_components/TextEditor.tsx
  src/app/(root-modal)/UploadModal/_components/TextEditorLoader.tsx
  src/app/(root-modal)/WarningForBigImage/WarningForBigImage.tsx
  src/app/layout.tsx
  src/components/Card/CardContainer.tsx
  src/components/Card/NoContent.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavigatorBoxButton.tsx
  src/components/SideBar/SideBar.tsx
  src/store/zustand.types.ts
Labels: 🔨 refactor, ✨ feat, 🎨 style, ✏ fix

#142 [송민혁] 팔로우 기능
  src/api/fetchRequestHandler.ts
  src/api/follow/deleteFollow.ts
  src/api/follow/postFollow.ts
  src/api/users/getUser.ts
  src/app/(root-modal)/ArtModal/ArtModal.tsx
  src/app/(root-modal)/EditUploadModal/EditUploadModal.tsx
  src/app/(root-modal)/UploadModal/UploadModal.tsx
  src/app/(root-modal)/_components/ModalHeader/ArtModalHeader.tsx
  src/app/(root-modal)/_components/ModalHeader/ModalHeader.tsx
  src/components/Button/Category/CategoryButton.tsx
  src/components/SideBar/SideBar.tsx
  src/styles/tailwind.css
Labels: 🚨 help, ✨ feat, 🎨 style

#148 [송규경] 사이드바 FIX, 팔로우 FIX, following 데이터 fetch 구현
  src/api/artworks/getFollowingArtworks.ts
  src/app/(root-modal)/_components/ModalHeader/ArtModalHeader.tsx
  src/components/Card/Card.tsx
  src/components/Card/CardContainer.tsx
  src/components/SideBar/SideBar.tsx
Labels: 🔨 refactor, ✨ feat, ✏ fix

#151 [송규경] 검색 기능 구현
  src/api/artworks/getSearchArtworks.ts
  src/app/(root-modal)/_components/ModalHeader/ArtModalHeader.tsx
  src/app/(unauth)/_components/Search/SearchCardSection.tsx
  src/app/(unauth)/_components/Search/SearchResult.tsx
  src/app/(unauth)/_components/SearchPage.tsx
  src/app/(unauth)/search/[searchWord]/page.tsx
  src/components/Card/Card.tsx
  src/components/Card/CardContainer.tsx
  src/components/FallbackUI/Card/CardImageFallbackUI.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/SearchBar.tsx
  src/hooks/useInfiniteData.tsx
  src/store/index.ts
  src/store/searchSlice.ts
  src/store/zustand.types.ts
Labels: ✨ feat, 🎨 style

#159 [이규호] 프로필 수정 페이지 반응형
  src/app/(auth)/_component/MyPage/MainContainer.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/myAccount/@deleteProfile/_component/DeleteBox.tsx
  src/app/(auth)/myAccount/layout.tsx
  src/app/(unauth)/_components/Artist/ArtistCardSection.tsx
  src/app/(unauth)/_components/Artist/ArtistLabelsGroup.tsx
  src/app/(unauth)/layout.tsx
  src/components/Button/Category/CategoryButtonGroup.tsx
  src/components/Input/Input.tsx
  src/components/Input/LinkInput.tsx
  src/components/ProfilePage/ProfilePage.tsx
  src/components/SideBar/SideBar.tsx
  src/components/Tab/Tab.tsx
  src/styles/tailwind.css
Labels: 🎨 style, ✏ fix

#158 [송민혁] 반응형 업로드 페이지, 반응형 상세 페이지
  public/assets/icons/Logout.svg
  public/assets/icons/QA.svg
  public/assets/icons/SettingIcon.svg
  src/app/(root-modal)/ArtModal/ArtModal.tsx
  src/app/(root-modal)/UploadModal/UploadModal.tsx
  src/app/(root-modal)/_components/ModalHeader/ModalHeader.tsx
  src/app/(unauth)/layout.tsx
  src/components/Comment/Comment.tsx
  src/components/Comment/CommentContainer.tsx
  src/components/Input/Input.tsx
  src/components/NavBar/NavigatorBox.tsx
  src/components/NavBar/ProfileImgDropDown.tsx
  src/components/SvgComponents/LogoutIcon.tsx
  src/components/SvgComponents/QAIcon.tsx
  src/components/SvgComponents/SettingIcon.tsx
  src/styles/tailwind.css
  tailwind.config.ts
Labels: 🎨 style

#163 [송규경] 작품이 없을 경우, NoContent 컴포넌트 뜨게 변경
  src/app/(auth)/_component/FollowingPage.tsx
  src/app/(auth)/_component/MyPage/MainContainer.tsx
  src/app/(auth)/following/layout.tsx
  src/app/(auth)/following/page.tsx
  src/app/(root-modal)/AskForLoginModal/AskForLoginModal.tsx
  src/app/(unauth)/_components/Artist/ArtistCardSection.tsx
  src/app/(unauth)/_components/Main/MainLabelsGroup.tsx
  src/components/Button/Category/CategoryButton.tsx
  src/components/Card/CardContainer.tsx
  src/components/NavBar/NavigatorBox.tsx
  src/components/NavBar/ProfileImgDropDown.tsx
  src/store/zustand.types.ts
Labels: ✨ feat, 🎨 style, ✏ fix

#164 [송규경] HotFix: cardContainer 위쪽 마진 원상복귀
  src/app/(auth)/_component/MyPage/MainContainer.tsx
  src/app/(unauth)/_components/Artist/ArtistCardSection.tsx
Labels: 🎨 style, ✏ fix
