Repository ArtTalkTalk/ArtTalkTalk_frontend, pull requests merged in 2024-01, with the labels that each got.

#4 chore: tailwind.css 파일 생성
  src/app/style/tailwind.css
Labels: ⚙ chore

#6 [chore]: 타입스크립트 설정 추가
  tsconfig.json
Labels: ⚙ chore

#8 [이규호] chore: react query 보일러 플레이트 설정
  package-lock.json
  package.json
  src/app/layout.tsx
  src/utils/react-query-provider.tsx
Labels: ⚙ chore

#9 [송규경] chore: styles 폴더 구조 및 tailwind.config.ts 수정
  src/app/layout.tsx
  src/styles/globals.css
  src/styles/tailwind.css
  tailwind.config.ts
Labels: ⚙ chore

#13 [김윤후] chore: workflows 폴더 생성, CI 파일 생성
  .github/workflows/ci.yml
Labels: ⚙ chore

#14 [김윤후] feat: page.tsx에 dev 브랜치 자동 배포 테스트용 글귀 작성
  src/app/page.tsx
Labels: ✨ feat

#15 [송규경] Chore/Design: Design System 세팅 및 Nested CSS warning 해결
  package-lock.json
  package.json
  postcss.config.js
  src/app/(auth)/[username]/_components/.gitkeep
  src/app/(auth)/[username]/page.tsx
  src/app/(auth)/[username]/status/[id]/.gitkeep
  src/app/layout.tsx
  src/app/page.tsx
  src/components/.gitkeep
  src/styles/globals.css
  tailwind.config.ts
Labels: ⚙ chore, 🎨 style, ✏ fix

#20 [김윤후] Feat: 카드 컴포넌트 구현
  public/assets/images/CommentImage.png
  public/assets/images/KebabImage.png
  public/assets/images/LikeImage.png
  public/assets/images/OnSaleImage.png
  public/assets/images/ViewImage.png
  src/components/card/card.tsx
  src/components/card/count.tsx
  src/components/card/kebabButton.tsx
Labels: ✨ feat, 🎨 style

#21 [이규호] Feat: 사이드바 컴포넌트 구현
  .prettierrc
  package-lock.json
  package.json
  public/Icons/default_profile.svg
  public/Icons/edit.svg
  public/Icons/link_icon.svg
  src/components/SideBar/EditIcon.tsx
  src/components/SideBar/LinkIcon.tsx
  src/components/SideBar/ProfileIcon.tsx
  src/components/SideBar/SideBar.tsx
  src/styles/tailwind.css
  tailwind.config.ts
Labels: ✨ feat, 🎨 style

#22 [송민혁] 카드 섹션 버튼 및 그리드 추가
  src/components/button/category/categoryButton.tsx
  src/components/button/category/categoryButtonGroup.tsx
  src/components/button/upload/uploadButton.tsx
  src/styles/tailwind.css
Labels: ✨ feat, 🎨 style

#23 [송규경] Nav bar / Login Modal / Button 합성 컴포넌트 구현
  prettier.config.js
  public/assets/icons/ProfileImg.svg
  public/assets/icons/message.svg
  public/assets/icons/search.svg
  public/assets/images/profileDropDown.svg
  public/assets/images/하니.jpg
  src/app/(auth)/[username]/[id]/.gitkeep
  src/app/(auth)/chatroom/[id]/.gitkeep
  src/app/(auth)/chatroom/layout.tsx
  src/app/(auth)/chatroom/page.tsx
  src/app/(unauth)/@modal/(.)flow/login/page.tsx
  src/app/(unauth)/@modal/default.tsx
  src/app/(unauth)/_components/LoginModal.tsx
  src/app/(unauth)/flow/login/page.tsx
  src/app/(unauth)/layout.tsx
  src/app/(unauth)/login/_components/RedirectToLogin.tsx
  src/app/(unauth)/login/page.tsx
  src/app/(unauth)/page.tsx
  src/app/page.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/NavigatorBox.tsx
  src/components/NavBar/ProfileImgDropDown.tsx
  src/components/NavBar/SearchBar.tsx
  src/components/button/KebabButton.tsx
  src/components/button/PrimaryButton.tsx
  src/components/button/category/categoryButtonGroup.tsx
  src/components/button/index.ts
  src/components/button/upload/uploadButton.tsx
  src/components/card/card.tsx
  src/hooks/useDropDown.ts
  src/hooks/useOnClickOutside.ts
  src/store/index.ts
  src/store/searchSlice.ts
  src/styles/globals.css
  src/styles/tailwind.css
  src/types/zustand.ts
  src/utils/react-query-provider.tsx
  tailwind.config.ts
Labels: 🔨 refactor, ✨ feat, 🎨 style

#34 [송민혁] 카테고리 버튼 string 대신 enum으로 타입 좁히기
  src/components/Button/Category/CategoryButton.types.ts
  src/components/Button/Category/CategoryButtonGroup.tsx
Labels: 🔨 refactor
